### ISSUE TITLE
Clock Face Discovery

### ISSUE THREAD

**Issue by mattcanty** [mattcanty/rain-clock#25]
Rain Clock needs a new clock. Here are some requirements off the top of my head.

1. Load with minimal interaction (ideally, only one to allow the usage of user's location)
2. Be a clock face
3. Precipitation forecast shown as:
    1. Blue depth denotes forecast's probability
    2. Reach of minute blue ware from edge of clock to centre denotes amount of rain
    3. There is a maximum
        1. If maximum is exceeded, could be signified with a different colour?
4. All the information needed is on one page
5. Info page which shows how the clock works
    1. Empty states
    2. This should be highlighted when the page and data has loaded but there is no rain forecasted
6. Animation
7. Responsive/Fast - High Google Lighthouse score

Future head-scratching:
- Tailwind
- Flutter/React native
- Progressive Web App
- Widgets - probably yes

Can use branch `clockface-discovery` for this

**Comment by mattcanty** [comment]
Looks QI https://github.com/liz-peng/p5.Polar

**Comment by Debens** [comment]
I've had a small play around for now with the main goal of having an interpolated line to represent the rain intensity over using bar segments.

There's probably a little more bloat on the branch than I think you'd prefer at the moment. For example, I've included React for now as that's just what I'm most comfortable with. There isn't a reason this can't be removed I've tried to keep most of the drawing logic framework agnostic.

The idea I'm going for is to have multiple different clock faces overlapping each other than can be included or removed. E.g. a face for intensity, a face for probability, and the actual clock face. You can have a face that does both in the combined manner I think you're aiming for but it's nice to have a cognitive split at the moment and can provide a more customizable experience in the future.

For drawing the faces I looked into some polar coordinates libraries but they all end up making you do the math yourself. The king of JS charts at the moment, and has always been [d3](https://github.com/d3/d3). It's very battle tested and super powerful, the downside is that it can be a little complicated at times and I'm not really an expert on it, however, there are lots and lots of examples and tutorials on the web. 

I've also added TS to save me the headaches JS provides, this does include an additional build step to compile to code. Webpack will do this and bundle everything into a single JS file. Some other quality of life improvements include prettier, I suggest getting the vscode plugin, or adding the extensions config to the repo.

There are a few small accessibility issues at the moment for larger screens, and the clock ticks still need a margin as they are clipped.

**Comment by Debens** [comment]
So far I've only had a few hours here and there in the evenings, and I'm working on hardware that's nearly a decade old at this point so it's been a little tough but the branch is in a mostly functional state at the moment. 

* Added [SWR](https://github.com/vercel/swr) for better data loading that will constantly refresh for as long as the tab is open, data won't reload if the tab isn't focused but will refresh when the user returns.
* Clock face is properly responsive for all screen sizes
* Water level is interpolated as an angular radius to avoid any issues with having bars overlapping
* Water level transitions on change 
* The simulated action has been refactored but works in the same manner for now (quick actions need to be "prettified" a bit but for now is functional.
* Hard-coded strings are moved onto the environment

The only missing feature that is a regression of functionality is having the water level radial area filled with a conic gradient. Turns out SVG doesn't support conic gradients which is a little frustrating. There are some ways to get around this as CSS does support conic-gradients but this is going to need some more work.

For now, it would be good to check it out, it's not the most beautiful at the moment and could do with some more animations and tooltips but to run all you need to do is build the JS bundle `yarn develop` and then you can view the HTML file.

An issue I have at the moment is that locally I don't have access to live data so I'm only working off the simulated data.

Next features:
* Conic gradient for probability
* Loading/Empty states
* Quick action buttons
* PWA
* Theme styles (dark/light/custom)
* Other clock faces
* Animate water level

**Comment by Debens** [comment]
Oh, and also looking at a proper location request flow, and what happens when denied

**Comment by mattcanty** [comment]
This is great stuff so far. I'll start looking at making deployments from branches by default then it's out there and you can actually use it with real rain data.

Man it rains so much in Lancaster. I use it literally all the time.

At least if I have access to this branch for a little while I can be testing it out as it changes.

**Comment by mattcanty** [comment]
I think discovery is done. So much great discovery.
